export const scenes = [
  { id: "problem", kind: "problem", label: "WHY", start: 0, duration: 13, light: false, caption: "In England, almost one in five pupils is persistently absent. But returning to school does not mean they are ready to rejoin the lesson.", narration: "In England, almost one in five pupils is persistently absent. When a pupil returns, the timetable has moved on. Returning to the building is only the beginning." },
  { id: "failure", kind: "failure", label: "THE OLD APPROACH", start: 13, duration: 14, light: false, caption: "After four weeks away, Mia faces twenty missed days, twelve resources, and a class that keeps moving. Catch up on everything is not a workable plan.", narration: "Mia is returning after four weeks away. She faces twenty missed days, twelve lesson resources, and a class beginning binary search. Catch up on everything is not a route back." },
  { id: "idea", kind: "idea", label: "THE IDEA", start: 27, duration: 16, light: true, caption: "BridgeBack asks a different question: what is the minimum this pupil needs to understand to take part in the next lesson?", narration: "BridgeBack asks a different question. What is the minimum this pupil needs to take part in the next lesson? It checks only the prerequisites and builds a teacher-approved route." },
  { id: "computer-science", kind: "computer-science", label: "COMPUTER SCIENCE", start: 43, duration: 20, light: false, caption: "For binary search, BridgeBack works backwards through teacher materials: twenty days become twelve resources, seven possible prerequisites, two support needs, and three focused activities.", narration: "For binary search, BridgeBack works backwards through the teacher's materials. Twenty missed days become twelve resources, seven possible prerequisites, two support needs, and three focused activities. Everything that does not unlock tomorrow's lesson stays out." },
  { id: "pupil", kind: "pupil", label: "THE PUPIL ROUTE", start: 63, duration: 17, light: true, caption: "Mia sees a calm check-in, no grades, and never more than three next steps. She can request a visual explanation or ask her teacher for help at any point.", narration: "Mia sees no grades, and never more than three next steps. Each activity includes a worked example and one quick check. She can request a visual or ask her teacher for help." },
  { id: "maths", kind: "maths", label: "MATHEMATICS", start: 80, duration: 15, light: false, caption: "The method transfers. Before simultaneous equations, Amina needs rearranging and substitution—not every algebra topic she missed.", narration: "The method transfers. Before simultaneous equations, Amina needs rearranging and substitution. She does not receive quadratics, inequalities, or every algebra topic she missed." },
  { id: "architecture", kind: "architecture", label: "RESPONSIBLE AI", start: 95, duration: 15, light: false, caption: "GPT-5.6 proposes the map, diagnostic and micro-lessons. GPT Image Mini adds optional visuals. Deterministic scoring and teacher approval keep the important decisions human.", narration: "GPT Five point Six proposes the map, diagnostic, and explanations. GPT Image Mini provides optional visuals. Scoring stays deterministic, sources remain visible, teachers approve the route, and pupils can ask for human help." },
  { id: "close", kind: "close", label: "BRIDGEBACK", start: 110, duration: 10, light: false, caption: "BridgeBack does not rebuild every missed lesson. It finds the shortest, teacher-approved path back into learning.", narration: "BridgeBack finds the shortest, teacher-approved path back into learning. Built with OpenAI for Build Week." },
] as const;

export const narrationText = scenes.map((scene) => scene.narration).join(" ");
