export const scenes = [
  { id: "problem", kind: "problem", label: "WHY", start: 0, duration: 13, light: false, caption: "In England, almost one in five pupils is persistently absent. But returning to school does not mean they are ready to rejoin the lesson.", narration: "In England, almost one in five pupils is persistently absent. When a pupil returns, the timetable has moved on. Returning to the building is only the beginning." },
  { id: "failure", kind: "failure", label: "THE OLD APPROACH", start: 13, duration: 14, light: false, caption: "After four weeks away, Mia faces twenty missed days, twelve resources, and a class that keeps moving. Catch up on everything is not a workable plan.", narration: "Mia is returning after four weeks away. She faces twenty missed days, twelve lesson resources, and a class beginning binary search. Catch up on everything is not a route back." },
  { id: "idea", kind: "idea", label: "THE IDEA", start: 27, duration: 16, light: true, caption: "BridgeBack turns absence from a backlog problem into a curriculum-reconnection problem.", narration: "BridgeBack starts with the destination: the lesson happening next. It works backwards through a teacher-reviewed curriculum graph to find a small, source-grounded route back into participation." },
  { id: "computer-science", kind: "computer-science", label: "COMPUTER SCIENCE", start: 43, duration: 20, light: false, caption: "For binary search, BridgeBack works backwards through teacher materials: twenty days become twelve resources, seven possible prerequisites, two support needs, and three focused activities.", narration: "For binary search, BridgeBack works backwards through the teacher's materials. Twenty missed days become twelve resources, seven possible prerequisites, two support needs, and three focused activities. Everything that does not unlock tomorrow's lesson stays out." },
  { id: "pupil", kind: "pupil", label: "THE PUPIL ROUTE", start: 63, duration: 17, light: true, caption: "Mia sees a calm check-in, no grades, and never more than three next steps. She can request a visual explanation or ask her teacher for help at any point.", narration: "Mia sees no grades, and never more than three next steps. Each activity includes a worked example and one quick check. She can request a visual or ask her teacher for help." },
  { id: "maths", kind: "maths", label: "MATHEMATICS", start: 80, duration: 15, light: false, caption: "The method transfers. Before simultaneous equations, Amina needs rearranging and substitution, not every algebra topic she missed.", narration: "The method transfers. Before simultaneous equations, Amina needs rearranging and substitution. She does not receive quadratics, inequalities, or every algebra topic she missed." },
  { id: "architecture", kind: "architecture", label: "BUILT WITH CODEX + GPT-5.6", start: 95, duration: 15, light: false, caption: "Sol maps sources, Terra drafts the approved diagnostic and Luna creates pupil-sized support. Scoring and graph traversal remain deterministic.", narration: "GPT Five point Six Sol maps sources, Terra drafts the diagnostic, and Luna creates pupil-sized support. Codex helped turn the product hypothesis into the two-sided Next.js, Convex and Clerk system, safety boundaries, mobile experience and tests." },
  { id: "close", kind: "close", label: "BRIDGEBACK", start: 110, duration: 10, light: false, caption: "The shortest teacher-approved path back into learning.", narration: "BridgeBack does not promise to recover four lost weeks. It gives teacher and pupil a manageable first step into the lesson already happening." },
] as const;

export const narrationText = scenes.map((scene) => scene.narration).join(" ");
